### ISSUE TITLE
does not work for nuxt ^2.5.1

### ISSUE THREAD

**Issue by HKskn** [fukuiretu/nuxt-user-agent#18]

**Comment by sonnh58** [comment]
I have same issue v1.1.0 and nuxt 2.5.1 when build
![image](https://user-images.githubusercontent.com/10656177/55377753-9fdf7300-5540-11e9-95b2-9cba1555952f.png)

downgrade v1.0.2 resolve problem.

**Comment by HKskn** [comment]
@sonnh58 same error that I experienced. To solve it I changed  another library named 'https://github.com/dotneet/nuxt-device-detect'

**Comment by sanguneo** [comment]
@sonnh58 same error ... I've downgrade the version then solved. (down to 1.0.2)

**Comment by pi0** [comment]
This error is because the module is mixing CJS with es (import) syntax.  (Thanks to @manniL for guiding me to here)

**Comment by pi0** [comment]
Created #19 for fix.

**Comment by fukuiretu** [comment]
I'm sorry everyone:bow::bow::bow: I will check the weekend so please wait a little more.

@pi0 Thank you for PR 🙏

**Comment by rchl** [comment]
@fukuiretu can you please handle PR? :)

**Comment by fukuiretu** [comment]
Sorry for the late response:bow: We just released v1.2.0(https://github.com/fukuiretu/nuxt-user-agent/releases/tag/v1.2.0) which merged #18

**Comment by fukuiretu** [comment]
This issue closes. Please reopen if the problem occurs again. thank you.
