### ISSUE TITLE
Avoid errors when executing the generate command. 

### ISSUE THREAD

**Issue by grandstar-uto** [fukuiretu/nuxt-user-agent#2]
Hi.  
I appreciate your great product :)

When building with the generate command, an error appears.

```bath
Cannot read property 'headers' of undefined
```

To avoid this error, change the reference to `ctx.req` as follows.

```js
export default (ctx, inject) => {
  let userAgent = "";
  if (typeof ctx.req !== "undefined") {
    userAgent = ctx.req.headers["user-agent"]
  } else if (typeof navigator !== "undefined") {
    userAgent = navigator.userAgent
  }

  ctx.$ua = detector(userAgent);
  inject("ua", detector(userAgent));
};
```

If you make this correction, the command will execute correctly.

Thanks !!

**Comment by fukuiretu** [comment]
@grandstar-uto Thank you for the issue. Surely the `nuxt generate` command is not considered.
I will bug fix it as soon as possible. Thank you 🙏

**Comment by fukuiretu** [comment]
@grandstar-uto I released bugfix earlier. Can you retry with v1.0.2?
Thank you for reporting this time!!
