### ISSUE TITLE
ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by HapLifeMan** [fukuiretu/nuxt-user-agent#23]
Hi there,

I updated the package today and my application isn't working anymore (on Nuxt 2.6.1).
Here's what I got in the console:

![Capture d’écran 2019-04-16 à 05 11 58](https://user-images.githubusercontent.com/1854141/56179505-40846700-6006-11e9-9563-3270dfacd60c.png)

References to:

![Capture d’écran 2019-04-16 à 05 12 08](https://user-images.githubusercontent.com/1854141/56179544-63168000-6006-11e9-844d-cfec624c8173.png)

Thanks :)

**Comment by sonnh58** [comment]
Same issue :(

**Comment by siberiadev** [comment]
Yeah, same here!

**Comment by fukuiretu** [comment]
I'm sorry everyone:bow: We have released v1.2.1(https://github.com/fukuiretu/nuxt-user-agent/releases/tag/v1.2.1) as a bugfix for this issue. Can you confirm?

**Comment by sonnh58** [comment]
It works now.

**Comment by fukuiretu** [comment]
This issue closes. Please reopen if the problem occurs again. thank you.
