### ISSUE TITLE
Browser Always Returns Chrome on Live

### ISSUE THREAD

**Issue by BenjjinF** [fukuiretu/nuxt-user-agent#4]
Works perfectly on a dev server but when deployed on firebase it always returns chrome.

**Comment by fukuiretu** [comment]
@BenjjinF sorry, could you give me an example?

**Comment by BenjjinF** [comment]
Sorry for the delay. The issue ended up being that ctx.req.headers was undefined when using npm run generate. Thus, it was was using DEFAULT_USER_AGENT.

Given that, you're likely limited to spa mode, components wrapped in <no-ssr>, etc.
